[2025-01-11T11:53:44.033+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-11T11:53:44.043+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dynamic_task_mapping_sequentials_dag.fetch_data manual__2025-01-11T11:53:41.385829+00:00 [queued]>
[2025-01-11T11:53:44.048+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dynamic_task_mapping_sequentials_dag.fetch_data manual__2025-01-11T11:53:41.385829+00:00 [queued]>
[2025-01-11T11:53:44.048+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-11T11:53:44.054+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_data> on 2025-01-11 11:53:41.385829+00:00
[2025-01-11T11:53:44.059+0000] {standard_task_runner.py:72} INFO - Started process 143 to run task
[2025-01-11T11:53:44.064+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dynamic_task_mapping_sequentials_dag', 'fetch_data', 'manual__2025-01-11T11:53:41.385829+00:00', '--job-id', '739', '--raw', '--subdir', 'DAGS_FOLDER/experiments/dynamic_task_mapping_sequentials_dag.py', '--cfg-path', '/tmp/tmpbrhv3_5w']
[2025-01-11T11:53:44.066+0000] {standard_task_runner.py:105} INFO - Job 739: Subtask fetch_data
[2025-01-11T11:53:44.098+0000] {task_command.py:467} INFO - Running <TaskInstance: dynamic_task_mapping_sequentials_dag.fetch_data manual__2025-01-11T11:53:41.385829+00:00 [running]> on host a2978c5b6b3a
[2025-01-11T11:53:44.148+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dynamic_task_mapping_sequentials_dag' AIRFLOW_CTX_TASK_ID='fetch_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-11T11:53:41.385829+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-11T11:53:41.385829+00:00'
[2025-01-11T11:53:44.150+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-11T11:53:44.880+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-11T11:53:44.939+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-11T11:53:44.940+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dynamic_task_mapping_sequentials_dag, task_id=fetch_data, run_id=manual__2025-01-11T11:53:41.385829+00:00, execution_date=20250111T115341, start_date=20250111T115344, end_date=20250111T115344
[2025-01-11T11:53:45.003+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-11T11:53:45.089+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-11T11:53:45.091+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
